### PR TITLE
Small QOL improvements

### PR DESCRIPTION
**Pull request by mariuskoeppen**
This will add some quality-of-life improvements:
* Add default `Trunk.toml` file from [the trunk repo](https://github.com/trunk-rs/trunk/blob/main/Trunk.toml) with some basic settings preconfigured. 
* Get prompted what channel (`stable`/`nightly`) to use and configure the files accordingly. 
* Get prompted if default VS Code editor settings should be added. This mainly configures the `rustfmt` command. In future we could add support for other text editors. 
* Change default from CSS to SCSS. In my opinion there are no downsides to SCSS over CSS.

### CODE REVIEW

**Comment by gbj** [comment]
This looks good to me overall! My one question has to do with the VS Code settings: if the user does not have `leptosfmt` installed, how does rust-analyzer handle this?

**Comment by mariuskoeppen** [comment]
When you don't have `leptosfmt` installed you will get the following error on saving:  
```
[Error - 8:20:34 AM] Request textDocument/formatting failed.
  Message: Failed to spawn cd "[project_path]/src/components" && "leptosfmt" "--stdin" "--rustfmt"
  Code: -32603
  ```
Only formatting will not work, otherwise everything is fine. We could mention in the Readme that `leptosfmt` should be installed manually.

**Comment by gbj** [comment]
Okay, thanks.

**Comment by mariuskoeppen** [comment]
This PR now also bumps leptos from 0.6 to 0.7

**Comment by gbj** [comment]
Thanks very much!

**Pull request merged**
